-- MySQL Script generated by MySQL Workbench
-- Sun 28 May 2017 07:27:33 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mammoth
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mammoth` ;

-- -----------------------------------------------------
-- Schema mammoth
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mammoth` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mammoth` ;

-- -----------------------------------------------------
-- Table `mammoth`.`sale_percentage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mammoth`.`sale_percentage` ;

CREATE TABLE IF NOT EXISTS `mammoth`.`sale_percentage` (
  `id` BIGINT(20) NOT NULL,
  `percent` DECIMAL NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `percent_UNIQUE` (`percent` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mammoth`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mammoth`.`product` ;

CREATE TABLE IF NOT EXISTS `mammoth`.`product` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(255) NULL,
  `barcode` VARCHAR(255) NOT NULL,
  `quantity` BIGINT(20) NOT NULL,
  `price` DECIMAL NOT NULL,
  `date` DATE NULL,
  `sale_percentage_id` BIGINT(20) NOT NULL,
  `self_life` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `barcode_UNIQUE` (`barcode` ASC),
  INDEX `fk_product_sale_percentage_idx` (`sale_percentage_id` ASC),
  CONSTRAINT `fk_product_sale_percentage`
    FOREIGN KEY (`sale_percentage_id`)
    REFERENCES `mammoth`.`sale_percentage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mammoth`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mammoth`.`user` ;

CREATE TABLE IF NOT EXISTS `mammoth`.`user` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `email` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mammoth`.`sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mammoth`.`sale` ;

CREATE TABLE IF NOT EXISTS `mammoth`.`sale` (
  `id` BIGINT(20) NOT NULL,
  `date` DATE NULL,
  `total_price` DECIMAL NULL,
  `user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sale_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_sale_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mammoth`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mammoth`.`sale_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mammoth`.`sale_product` ;

CREATE TABLE IF NOT EXISTS `mammoth`.`sale_product` (
  `sale_id` BIGINT(20) NOT NULL,
  `product_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`sale_id`, `product_id`),
  INDEX `fk_sale_has_product_product1_idx` (`product_id` ASC),
  INDEX `fk_sale_has_product_sale1_idx` (`sale_id` ASC),
  CONSTRAINT `fk_sale_has_product_sale1`
    FOREIGN KEY (`sale_id`)
    REFERENCES `mammoth`.`sale` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mammoth`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
